ALTER TABLE entries ADD COLUMN IF NOT EXISTS request_id TEXT UNIQUE;
CREATE TABLE IF NOT EXISTS repayments (id BIGSERIAL PRIMARY KEY, from_id BIGINT NOT NULL REFERENCES members(id), to_id BIGINT NOT NULL REFERENCES members(id), currency TEXT NOT NULL, minor BIGINT NOT NULL CHECK(minor > 0), date TEXT NOT NULL, request_id TEXT UNIQUE);
