const {spawn}=require('node:child_process');const http=require('http');const assert=require('node:assert/strict');const fs=require('fs');
const dir=fs.mkdtempSync('/tmp/xiaoben-integration-');
const mock=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.url.includes('currencies'))return res.end('[]');if(req.url.includes('/rate/'))return res.end(JSON.stringify({date:'2026-10-02',base:'HKD',quote:'CNY',rate:0.9}));res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({title:'测试晚餐',date:'2026-10-02',currency:'CNY',total:100,payerName:'我',participants:['我','新朋友'],category:'dining',confidence:1,warnings:[]})}}]}));});
(async()=>{await new Promise(r=>mock.listen(3057,'127.0.0.1',r));const proc=spawn(process.execPath,['app/server.js'],{env:{...process.env,LOCAL_DB_DIR:dir,APP_PORT:'3056',ARK_API_KEY:'TEST-ONLY-NOT-A-REAL-KEY',ARK_MODEL:'test-model',ARK_BASE_URL:'http://127.0.0.1:3057',FX_BASE_URL:'http://127.0.0.1:3057'},stdio:['ignore','pipe','pipe']});let logs='';proc.stdout.on('data',x=>logs+=x);proc.stderr.on('data',x=>logs+=x);
 const call=async(path,data,method='POST')=>{const r=await fetch('http://127.0.0.1:3056/api'+path,{method:data?method:'GET',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const j=await r.json();assert.ok(r.ok,JSON.stringify(j));return j;};
 try{for(let i=0;i<100;i++){await new Promise(r=>setTimeout(r,100));if(logs.includes('listening'))break;}assert.ok(logs.includes('listening'),logs);
 await call('/profile',{nickname:'qiqi'},'PUT');const parsed=await call('/ai/parse',{text:'昨天我和新朋友吃饭100元，我付，平摊'});assert.equal(parsed.draft.createdMembers[0],'新朋友');assert.equal(parsed.draft.categoryId,'dining');assert.equal(parsed.draft.participants.length,2);assert.ok(parsed.draft.participants.every(m=>m.id));
 const d=parsed.draft;const payload={...d,splits:d.splitSuggestion,fx:{HKD:{from:'CNY',rate:'1.1',source:'manual'}},requestId:'repeat-test'};const first=await call('/entries',payload);const second=await call('/entries',payload);assert.equal(first.entry.id,second.entry.id);assert.equal(first.entry.fx.HKD.rate,'1.1');
 const before=(await call('/entries')).entries;assert.equal(before.length,1);await call('/members/'+d.payerId,{name:'QiQi'},'PATCH');const {members}=await call('/members');const accounting=require('../shared/accounting.cjs');const balance=accounting.settle(before,members);assert.equal(balance.balances.find(b=>b.name==='QiQi').net,5000);
 const transfer=balance.transfers[0];await call('/repayments',{fromId:transfer.fromId,toId:transfer.toId,minor:transfer.amount,currency:'CNY',date:'2026-10-03',requestId:'repay-test'});const {repayments}=await call('/repayments');assert.equal(accounting.settle(before,members,repayments).transfers.length,0);
 console.log('PASS: AI response parsing (mock upstream), auto member creation, category, FX persistence, idempotent save, rename identity, repayment closure');
 }finally{proc.kill('SIGTERM');mock.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
